spring:
  application:
    name: currency-service
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8081

request:
  cbrf:
    domain: http://www.cbr.ru/scripts/
    all-currency: XML_daily.asp